### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jgoppert** [aozturk/HashMap#2]
I want to give you credit for this, are you OK with releasing it as BSD 3 clause. Using it here for an embedded environment without stl: https://github.com/PX4/Firmware/pull/6045

**Comment by aozturk** [comment]
Hi James,
Of course, thanks for giving a heads up. I've updated the license of the repository to be under Apache 2.0 license, which I hope is permissive enough. If it doesn't work, please let me know.

**Comment by jgoppert** [comment]
Awesome, thanks!
